# GitGuardian Configuration for myAdmin
# https://docs.gitguardian.com/ggshield-docs/reference/configuration

version: 2

# Secret detection settings
secret:
  # Don't show actual secret values in output (security)
  show_secrets: false
  
  # Paths to exclude from scanning
  ignored_paths:
    - "**/.venv/**"
    - "**/venv/**"
    - "**/node_modules/**"
    - "**/.git/**"
    - "**/build/**"
    - "**/dist/**"
    - "**/__pycache__/**"
    - "**/*.pyc"
    - "**/mysql_data/**"
    - "**/logs/**"
    - "**/.pytest_cache/**"
    - "**/.hypothesis/**"
    - "**/coverage/**"
    - "**/*.log"
    - "**/terraform.tfstate*"
    - "**/.terraform/**"
    - "**/*.example"
    - "**/example.*"
    - "**/*-example.*"
    - "**/*.md"
  
  # Ignore known test/placeholder secrets
  ignored_matches:
    - name: "Test API Keys"
      match: "sk-test-"
    - name: "Example placeholders"
      match: "your-.*-here"
    - name: "Placeholder values"
      match: "REPLACE_ME|YOUR_.*|EXAMPLE_.*"
    - name: "Localhost URLs"
      match: "http://localhost"

# Exit with error code if secrets found (fail the commit)
exit_zero: false

# Verbose output for debugging
verbose: false

# Maximum commits to scan in pre-commit hook
max_commits_for_hook: 50
