-- Create or replace view that combines bnb (actuals) and bnbplanned (future bookings)
-- This view is used for reporting and analysis across all bookings
DROP VIEW IF EXISTS vw_bnb_total;
CREATE VIEW vw_bnb_total AS
SELECT id,
    sourceFile,
    channel,
    listing,
    checkinDate,
    checkoutDate,
    nights,
    guests,
    amountGross,
    amountNett,
    amountChannelFee,
    amountTouristTax,
    amountVat,
    guestName,
    phone,
    reservationCode,
    reservationDate,
    status,
    pricePerNight,
    daysBeforeReservation,
    addInfo,
    year,
    q,
    m,
    'actual' AS source_type -- Add indicator for actual bookings
FROM bnb
UNION ALL
-- Use UNION ALL for better performance (no duplicate removal needed)
SELECT id,
    sourceFile,
    channel,
    listing,
    checkinDate,
    checkoutDate,
    nights,
    guests,
    amountGross,
    amountNett,
    amountChannelFee,
    amountTouristTax,
    amountVat,
    guestName,
    phone,
    reservationCode,
    reservationDate,
    status,
    pricePerNight,
    daysBeforeReservation,
    addInfo,
    year,
    q,
    m,
    'planned' AS source_type -- Add indicator for planned bookings
FROM bnbplanned;