-- Seed tenant parameters for Railway (cleaned)
-- Only valid per-tenant params: report_output_path, google_drive_folder_id
INSERT IGNORE INTO parameters (
        scope,
        scope_id,
        namespace,
        `key`,
        value,
        value_type,
        is_secret,
        created_by
    )
VALUES (
        'tenant',
        'GoodwinSolutions',
        'storage',
        'report_output_path',
        '"/app/reports"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'GoodwinSolutions',
        'storage',
        'google_drive_folder_id',
        '"0B9OBNkcEDqv1YWQzZDkyM2YtMTE4Yy00ODUzLWIzZmEtMTQ1NzEzMDQ1N2Ix"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'InterimManagement',
        'storage',
        'report_output_path',
        '"/app/reports"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'InterimManagement',
        'storage',
        'google_drive_folder_id',
        '"0B9OBNkcEDqv1YWQzZDkyM2YtMTE4Yy00ODUzLWIzZmEtMTQ1NzEzMDQ1N2Ix"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'kimengerbrand',
        'storage',
        'report_output_path',
        '"/app/reports"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'kimengerbrand',
        'storage',
        'google_drive_folder_id',
        '"0B9OBNkcEDqv1YWQzZDkyM2YtMTE4Yy00ODUzLWIzZmEtMTQ1NzEzMDQ1N2Ix"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'myAdmin',
        'storage',
        'report_output_path',
        '"/app/reports"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'myAdmin',
        'storage',
        'google_drive_folder_id',
        '"0B9OBNkcEDqv1YWQzZDkyM2YtMTE4Yy00ODUzLWIzZmEtMTQ1NzEzMDQ1N2Ix"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'PeterPrive',
        'storage',
        'report_output_path',
        '"/app/reports"',
        'string',
        0,
        'seed_migration'
    ),
    (
        'tenant',
        'PeterPrive',
        'storage',
        'google_drive_folder_id',
        '"0B9OBNkcEDqv1YWQzZDkyM2YtMTE4Yy00ODUzLWIzZmEtMTQ1NzEzMDQ1N2Ix"',
        'string',
        0,
        'seed_migration'
    );