/**
 * MemberMailCompose — the SES mail compose modal for a member set (C6, task 9.2).
 *
 * Opened from the Mail button in the capability-gated `pivot-result-actions`
 * slot (where the CSV button already lives), this keyboard-accessible Chakra
 * modal lets a user compose and send a mail to the members in the current
 * filtered-list / pivot result (R4.12, R8.4).
 *
 * What it does (design C6):
 *   - **Editable subject + body**, seeded from a BILINGUAL template
 *     (`members:analytics.mail.subjectTemplate` / `bodyTemplate`, task 0.3) — the
 *     user edits before sending. No hardcoded English (every label resolves from
 *     the `members` namespace, bilingual via the active language).
 *   - **Optional attachments**: "Attach CSV" (of the current result) and "Attach
 *     PDF labels" (only offered when the tenant's `address_mapping` resolves, so
 *     a tenant without address fields never sees a dead toggle). Both produce
 *     already-generated bytes the backend forwards to SES (CSV via `csvExport.ts`,
 *     PDF via the jsPDF address-label generator) — this UI base64-encodes them.
 *   - **Recipient resolution**: the recipient EMAIL field is resolved from
 *     `fieldConfig` / `analytics.field_roles` via {@link resolveEmailField}
 *     (R4.12), NOT hardcoded. The recipient list is the result rows that carry a
 *     resolvable, de-duplicated email.
 *   - **Recipient COUNT for confirmation before send** (R8.4): the modal shows
 *     the count and sends via a confirmed action — never a fire-and-forget click.
 *     BCC is the default (the backend BCCs every recipient).
 *   - **POST** to `/api/members/mail-set` via the authenticated
 *     {@link mailMembersSet} service; a success / error toast follows. An SES
 *     RATE LIMIT (task 9.3, R4.12) is surfaced with the dedicated bilingual
 *     `toast.rateLimited` message rather than the generic error, and the composed
 *     set is kept (the modal stays open to retry); every other failure shows the
 *     generic error toast, also keeping the set.
 *   - **Transient artifact cleanup (R8.5):** the generated CSV/PDF attachment
 *     bytes are released from memory after the send completes (success OR
 *     failure) — never silently accumulated across sends.
 *
 * Read-only w.r.t. member data: it only mails; it never mutates a member.
 *
 * @module components/members/analytics/MemberMailCompose
 * @see .kiro/specs/Members/member-analytics (design C6; requirements R4.12, R8.4)
 */

import React, { useEffect, useMemo, useState } from 'react';
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  ModalCloseButton,
  Button,
  Checkbox,
  FormControl,
  FormLabel,
  Input,
  Textarea,
  Text,
  VStack,
  useToast,
} from '@chakra-ui/react';
import { useTypedTranslation } from '../../../hooks/useTypedTranslation';
import type { FieldConfig, MemberRow } from '../../../types/members';
import { resolveEmailField, resolveAddressMapping } from './analyticsConfig';
import {
  mailMembersSet,
  type MailAttachment,
} from '../../../services/memberMailService';

/** `members`-namespace i18n key prefix for every label this modal renders. */
const T = 'analytics.mail';

export interface MemberMailComposeProps {
  /** Whether the modal is open. */
  isOpen: boolean;
  /** Close handler (overlay / Escape / Cancel). */
  onClose: () => void;
  /** The resolved field config — resolves the recipient email field + address mapping. */
  fieldConfig: FieldConfig | null;
  /**
   * The recipient member rows — the current filtered-list / pivot result rows
   * (`PivotResult.data`). The recipient email is read off each row by the
   * resolved email field key. These are the SAME rows the result table shows, so
   * the mail is scope-correct by construction (R8.2).
   */
  recipients: MemberRow[];
  /** Active language for bilingual label resolution + the seeded template. */
  language: string;
  /**
   * Produce the CSV bytes of the current result, base64 encoded, when the user
   * opts to attach CSV. Supplied by the Pivot Views panel (which owns the
   * result → CSV mapping via `csvExport.ts`). Absent → the CSV toggle is hidden.
   */
  buildCsvBase64?: () => string | null;
  /**
   * Produce the PDF-label bytes of the current result, base64 encoded, when the
   * user opts to attach PDF labels. Supplied by the panel (jsPDF generator).
   * Absent, OR the tenant has no resolvable `address_mapping` → the PDF toggle is
   * hidden (R4.10).
   */
  buildPdfBase64?: () => string | null;
  /** Optional audit label for the set being mailed (metadata only, R8.1). */
  setKey?: string;
}

/**
 * Resolve a `{nl,en}`-style template key to the active language's seed text.
 * Falls back through the i18n layer, so a missing active-language value still
 * yields a usable (non-English-hardcoded) default.
 */
export const MemberMailCompose: React.FC<MemberMailComposeProps> = ({
  isOpen,
  onClose,
  fieldConfig,
  recipients,
  language,
  buildCsvBase64,
  buildPdfBase64,
  setKey,
}) => {
  const { t } = useTypedTranslation('members');
  const toast = useToast();

  // The recipient email field, resolved from fieldConfig / analytics.field_roles
  // (R4.12) — never hardcoded. `undefined` → no email field configured, so the
  // send is blocked with a bilingual reason rather than mailing nothing.
  const emailField = useMemo(
    () => resolveEmailField(fieldConfig ?? undefined),
    [fieldConfig],
  );

  // The de-duplicated recipient emails read off the result rows via the resolved
  // field key. The COUNT of these is what the modal surfaces for confirmation
  // before send (R8.4). Blank / missing values are skipped; the backend repeats
  // this resolution authoritatively, so the count shown matches what is sent.
  const recipientEmails = useMemo<string[]>(() => {
    if (!emailField) {
      return [];
    }
    const seen = new Set<string>();
    const out: string[] = [];
    for (const row of recipients ?? []) {
      const raw = (row as Record<string, unknown>)[emailField];
      if (raw === null || raw === undefined) {
        continue;
      }
      const normalized = String(raw).trim().toLowerCase();
      if (normalized && !seen.has(normalized)) {
        seen.add(normalized);
        out.push(normalized);
      }
    }
    return out;
  }, [recipients, emailField]);

  const recipientCount = recipientEmails.length;

  // Whether PDF-label attachment is offered: the tenant must have a resolvable
  // address mapping AND the panel must supply a PDF builder (R4.10).
  const canAttachPdf = useMemo(
    () =>
      typeof buildPdfBase64 === 'function' &&
      Object.keys(resolveAddressMapping(fieldConfig ?? undefined)).length > 0,
    [buildPdfBase64, fieldConfig],
  );
  const canAttachCsv = typeof buildCsvBase64 === 'function';

  const [subject, setSubject] = useState('');
  const [body, setBody] = useState('');
  const [attachCsv, setAttachCsv] = useState(false);
  const [attachPdf, setAttachPdf] = useState(false);
  const [sending, setSending] = useState(false);
  // The two-step confirm (R8.4): the first Send press asks for confirmation
  // (showing the recipient count); the second actually sends.
  const [confirming, setConfirming] = useState(false);

  // Seed the subject/body from the bilingual template each time the modal opens,
  // and reset the attach toggles + confirm step. Keyed on open only so re-renders
  // never clobber the user's edits mid-compose.
  useEffect(() => {
    if (!isOpen) {
      return;
    }
    setSubject(t(`${T}.subjectTemplate`));
    setBody(t(`${T}.bodyTemplate`));
    setAttachCsv(false);
    setAttachPdf(false);
    setConfirming(false);
    setSending(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen]);

  // Any change to the composed mail cancels a pending confirmation, so the user
  // always confirms the exact mail they are about to send.
  const resetConfirm = () => setConfirming(false);

  const trimmedSubject = subject.trim();
  const canSend =
    !!emailField &&
    recipientCount > 0 &&
    trimmedSubject !== '' &&
    body.trim() !== '' &&
    !sending;

  const buildAttachments = (): MailAttachment[] => {
    const attachments: MailAttachment[] = [];
    if (attachCsv && buildCsvBase64) {
      const csv = buildCsvBase64();
      if (csv) {
        attachments.push({ kind: 'csv', content_base64: csv, filename: 'members.csv' });
      }
    }
    if (attachPdf && canAttachPdf && buildPdfBase64) {
      const pdf = buildPdfBase64();
      if (pdf) {
        attachments.push({ kind: 'pdf', content_base64: pdf, filename: 'labels.pdf' });
      }
    }
    return attachments;
  };

  const handleSend = async () => {
    if (!canSend || !emailField) {
      return;
    }
    // First press → confirm (show the recipient count, R8.4). Second → send.
    if (!confirming) {
      setConfirming(true);
      return;
    }

    setSending(true);
    // The transient CSV/PDF attachment bytes this send holds in memory (R8.5).
    // Built once here, forwarded to the service, then explicitly released in the
    // `finally` below — on success OR failure — so a bulk mail never leaves the
    // generated member-data buffers lingering in memory.
    let attachments: MailAttachment[] = buildAttachments();
    try {
      const result = await mailMembersSet({
        recipients: recipients ?? [],
        subject: trimmedSubject,
        body,
        email_field: emailField,
        attachments,
        set_key: setKey,
      });

      if (result.success) {
        toast({ title: t(`${T}.toast.success`), status: 'success' });
        onClose();
      } else if (result.rateLimited) {
        // SES rate-limited the send (R4.12): show the DEDICATED bilingual message,
        // NOT the generic error. The composed set is NOT lost — the modal stays
        // open and the attach toggles are preserved so the user can retry.
        toast({ title: t(`${T}.toast.rateLimited`), status: 'warning' });
        setConfirming(false);
      } else {
        // Generic error toast for any other failure. The set result is NOT lost —
        // the modal stays open.
        toast({ title: t(`${T}.toast.error`), status: 'error' });
        setConfirming(false);
      }
    } catch {
      toast({ title: t(`${T}.toast.error`), status: 'error' });
      setConfirming(false);
    } finally {
      setSending(false);
      // Release the in-memory attachment buffers regardless of outcome (R8.5):
      // drop each descriptor's base64 payload, then the array itself, so the
      // generated CSV/PDF bytes are not retained after the send completes.
      for (const att of attachments) {
        att.content_base64 = '';
      }
      attachments = [];
    }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="xl" isCentered scrollBehavior="inside">
      <ModalOverlay />
      <ModalContent bg="gray.800" color="white" data-testid="member-mail-compose">
        <ModalHeader>{t(`${T}.title`)}</ModalHeader>
        <ModalCloseButton />
        <ModalBody>
          <VStack align="stretch" spacing={4}>
            {/* Recipient count for confirmation before send (R8.4). Also the
                "no email field" reason when the tenant has none configured. */}
            {emailField ? (
              <Text
                fontSize="sm"
                color={recipientCount > 0 ? 'orange.300' : 'yellow.300'}
                data-testid="member-mail-recipient-count"
              >
                {recipientCount > 0
                  ? t(`${T}.recipientCount`, { count: recipientCount })
                  : t(`${T}.recipientCountZero`)}
              </Text>
            ) : (
              <Text fontSize="sm" color="yellow.300" data-testid="member-mail-no-email-field">
                {t(`${T}.noEmailField`)}
              </Text>
            )}

            {/* Editable subject (seeded from the bilingual template). */}
            <FormControl isRequired>
              <FormLabel htmlFor="member-mail-subject">{t(`${T}.subject`)}</FormLabel>
              <Input
                id="member-mail-subject"
                data-testid="member-mail-subject"
                value={subject}
                onChange={(e) => {
                  setSubject(e.target.value);
                  resetConfirm();
                }}
                bg="gray.900"
              />
            </FormControl>

            {/* Editable body (seeded from the bilingual template). */}
            <FormControl isRequired>
              <FormLabel htmlFor="member-mail-body">{t(`${T}.body`)}</FormLabel>
              <Textarea
                id="member-mail-body"
                data-testid="member-mail-body"
                value={body}
                onChange={(e) => {
                  setBody(e.target.value);
                  resetConfirm();
                }}
                rows={8}
                bg="gray.900"
              />
            </FormControl>

            {/* Optional attachments — CSV always (if the panel supplies a
                builder); PDF labels only when the address mapping resolves. */}
            {canAttachCsv && (
              <Checkbox
                isChecked={attachCsv}
                onChange={(e) => {
                  setAttachCsv(e.target.checked);
                  resetConfirm();
                }}
                colorScheme="orange"
                data-testid="member-mail-attach-csv"
              >
                {t(`${T}.attachCsv`)}
              </Checkbox>
            )}
            {canAttachPdf && (
              <Checkbox
                isChecked={attachPdf}
                onChange={(e) => {
                  setAttachPdf(e.target.checked);
                  resetConfirm();
                }}
                colorScheme="orange"
                data-testid="member-mail-attach-pdf"
              >
                {t(`${T}.attachPdf`)}
              </Checkbox>
            )}

            {/* The confirmation prompt shown after the first Send press (R8.4). */}
            {confirming && (
              <Text fontSize="sm" color="orange.200" data-testid="member-mail-confirm">
                {t(`${T}.confirm`, { count: recipientCount })}
              </Text>
            )}
          </VStack>
        </ModalBody>
        <ModalFooter>
          <Button variant="ghost" mr={3} onClick={onClose} data-testid="member-mail-cancel">
            {t(`${T}.cancel`)}
          </Button>
          <Button
            colorScheme="orange"
            onClick={handleSend}
            isDisabled={!canSend}
            isLoading={sending}
            data-testid="member-mail-send"
          >
            {t(`${T}.send`)}
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
};

export default MemberMailCompose;
