/**
 * memberMailService — authenticated client for the member-set SES mail route
 * (member-analytics task 9.2, Design C6).
 *
 * Thin wrapper over `apiService.authenticatedPost` that POSTs a composed mail to
 * `POST /api/members/mail-set` (the Flask route from task 9.1). The backend:
 *   - resolves the tenant from the verified auth context (never trusts a
 *     client-supplied tenant, R8.2);
 *   - BCCs every recipient by default so a bulk send never leaks the list (R8.4);
 *   - gates on the `members:export` capability (same as CSV / PDF export).
 *
 * This service only shapes + sends the request and surfaces a typed result; the
 * compose UI (task 9.2) owns the subject/body template, recipient-count
 * confirmation, and the success/error toast. SES rate-limit-specific handling is
 * task 9.3 — this service returns the backend's status so the caller can branch.
 *
 * @module services/memberMailService
 * @see .kiro/specs/Members/member-analytics (design C6; requirements R4.12, R8.4)
 */

import { authenticatedPost, buildEndpoint } from './apiService';

/** The attachment kinds the backend forwards to SES (`csv` | `pdf`, task 9.1). */
export type MailAttachmentKind = 'csv' | 'pdf';

/**
 * One attachment to post to the mail route: already-generated bytes, base64
 * encoded. The frontend produces CSV bytes via `csvExport.ts` and PDF-label
 * bytes via the jsPDF address-label generator (task 8.2); this just carries them.
 */
export interface MailAttachment {
  /** Drives the default content type / extension on the backend. */
  kind: MailAttachmentKind;
  /** Base64-encoded file bytes (no data-URI prefix). */
  content_base64: string;
  /** Optional filename override (defaults to `members.<ext>` server-side). */
  filename?: string;
}

/** The request body for `POST /api/members/mail-set`. */
export interface MailMembersSetRequest {
  /**
   * The recipient member rows (or plain email strings). The backend reads each
   * row's email from `email_field` (resolved by the caller from `fieldConfig` /
   * `analytics.field_roles`, R4.12) then de-duplicates.
   */
  recipients: Array<Record<string, unknown> | string>;
  /** The mail subject (required, non-empty). */
  subject: string;
  /** The mail body (HTML or plain text, required, non-empty). */
  body: string;
  /** The field key to read each recipient's email from (R4.12). */
  email_field?: string;
  /** Optional CSV / PDF attachments. */
  attachments?: MailAttachment[];
  /** Optional audit label for the set that was mailed (metadata only, R8.1). */
  set_key?: string;
}

/** The parsed outcome of a mail-set send. */
export interface MailMembersSetResult {
  /** Whether the send succeeded. */
  success: boolean;
  /** How many recipients the backend resolved + BCC'd. */
  recipientCount?: number;
  /** The SES message id on success. */
  messageId?: string;
  /** The backend error message on failure. */
  error?: string;
  /**
   * The HTTP status. `429` signals an SES rate limit the caller surfaces
   * specifically (task 9.3); everything else is a generic error (task 9.2).
   */
  status: number;
  /**
   * `true` when the backend reported an SES rate limit / throttle (task 9.3,
   * R4.12) — a distinct, recoverable failure. The route answers `429` with a
   * `code: "rate_limited"`; the compose UI branches on this to show the dedicated
   * bilingual "send rate limit reached" message (NOT the generic error) and keeps
   * the composed set so the user can retry.
   */
  rateLimited?: boolean;
}

/**
 * Send a composed mail to a filtered member set via the backend SES route.
 *
 * Never throws for an HTTP error status — a non-2xx response is parsed into a
 * `{ success: false, status, error }` result so the compose UI can branch on the
 * status (generic error now, SES-rate-limit handling in task 9.3). A genuine
 * network/parse failure still rejects.
 */
export async function mailMembersSet(
  request: MailMembersSetRequest,
): Promise<MailMembersSetResult> {
  const res = await authenticatedPost(buildEndpoint('/api/members/mail-set'), request);

  // The route always answers JSON (success or error); tolerate a missing body.
  const body = (await res.json().catch(() => ({}))) as {
    success?: boolean;
    recipient_count?: number;
    message_id?: string;
    error?: string;
    message?: string;
    code?: string;
  };

  if (!res.ok || !body.success) {
    // An SES rate limit is a distinct, recoverable failure (task 9.3): the route
    // answers 429 with `code: "rate_limited"`. Flag it so the compose UI shows the
    // dedicated message and keeps the set, rather than the generic error.
    const rateLimited = res.status === 429 || body.code === 'rate_limited';
    return {
      success: false,
      status: res.status,
      error: body.error || body.message || `Request failed with status ${res.status}`,
      rateLimited,
    };
  }

  return {
    success: true,
    status: res.status,
    recipientCount: body.recipient_count,
    messageId: body.message_id,
  };
}
