"""
Member Analytics — SES Mail Route (member-analytics task 9.1, Design C6)

Endpoint for mailing a filtered/analytics member set via AWS SES with an optional
CSV / PDF-label attachment. Mirrors the ``tenant_admin_email.py`` pattern:
blueprint + ``cognito_required`` gating + tenant resolved from the auth context +
request parsing + delegation to ``SESEmailService`` + standardized error handling.

Scope / tenancy (R8.2):
    The tenant is ALWAYS resolved from the verified auth context
    (``get_current_tenant``) — a client-supplied tenant is never trusted. The
    recipient set is the rows the analytics page already resolved from the
    scope-narrowed ``GET /members`` (SAM module), so the mail is scope-correct by
    construction; this route does not widen that set.

Capability gate (R4.12):
    ``members:export`` — the same capability that gates CSV / PDF-label export.
    Enforced via ``cognito_required(required_permissions=[...])`` which expands the
    caller's tenant roles through ``ROLE_PERMISSIONS`` (Members_Export / Members_CRUD
    grant ``members:export``).

Safety (R8.4):
    Recipients are placed on BCC by default; the send goes to a single visible
    envelope recipient (the configured SES sender) with everyone else BCC'd, so a
    bulk mail never leaks the recipient list.

SES rate limiting (R4.12, Design C6 / ODI-4):
    AWS SES enforces a per-identity maximum send rate; when it is exceeded SES
    answers with a throttling ``ClientError`` (``Throttling`` /
    ``ThrottlingException`` / ``Throughput`` / "maximum sending rate exceeded").
    ``SESEmailService`` already folds that into its ``{success: False, error: ...}``
    result, so this route detects the throttle by matching the known throttling
    markers in that error and maps it to a DISTINCT ``429`` response carrying a
    machine-readable ``code: "rate_limited"`` — separate from the generic ``502``
    for any other SES failure. The compose UI branches on that to show the
    dedicated bilingual "send rate limit reached" message and keeps the set so the
    user can retry.

Transient artifacts (R8.5):
    The decoded attachment bytes (CSV / PDF held in memory to attach) are the only
    transient artifact this route holds; it writes NO temp file. Those bytes are
    explicitly released after the send completes — success OR failure — via a
    ``finally`` block, so a bulk mail never silently accumulates member PII in
    process memory.

The mail compose UI is task 9.2.
"""

import base64
import binascii
import logging

from flask import Blueprint, jsonify, request
from flask.typing import ResponseReturnValue

from auth.cognito_utils import cognito_required
from auth.tenant_context import get_current_tenant

logger = logging.getLogger(__name__)

members_mail_bp = Blueprint("members_mail", __name__)

# Capability that gates every member export surface (CSV / PDF / mail), per Design C6.
CAP_MEMBERS_EXPORT = "members:export"

# Accepted attachment "kind" labels and their default content types / extensions.
# The frontend attaches already-generated bytes (CSV from csvExport.ts, PDF labels
# from the jsPDF generator); this route just forwards them to SES.
_ATTACHMENT_KINDS = {
    "csv": {"content_type": "text/csv", "ext": "csv"},
    "pdf": {"content_type": "application/pdf", "ext": "pdf"},
}

# Markers that identify an SES rate-limit / throttling failure (R4.12, ODI-4).
# SES surfaces a throttled send as a ClientError whose code is one of
# ``Throttling`` / ``ThrottlingException``, or whose message mentions the
# throughput / maximum-sending-rate quota. ``SESEmailService`` folds the error
# into ``"<Code>: <Message>"``, so we match these markers case-insensitively
# against that string to distinguish a rate limit from any other SES failure.
_SES_THROTTLE_MARKERS = (
    "throttling",
    "throttlingexception",
    "throughput",
    "maximum sending rate exceeded",
    "max sending rate",
    "rate exceeded",
    "sending rate",
)


def _is_ses_rate_limited(error: str | None) -> bool:
    """Does an SES error string indicate a rate limit / throttle (R4.12)?

    ``SESEmailService`` returns throttling failures as ``"<Code>: <Message>"``
    (e.g. ``"Throttling: Maximum sending rate exceeded"``). This matches the known
    throttling markers case-insensitively so the route can map that single failure
    class to a distinct 429 rather than the generic 502.
    """
    if not error:
        return False
    haystack = error.lower()
    return any(marker in haystack for marker in _SES_THROTTLE_MARKERS)


def _extract_emails(recipients: list, email_field: str | None) -> list[str]:
    """Pull recipient email addresses out of the posted member rows.

    Accepts either a list of plain email strings, or a list of member-row dicts.
    For dicts, the email is read from ``email_field`` (resolved by the caller from
    ``fieldConfig`` / ``analytics.field_roles`` per R4.12) when provided, else from a
    small set of conventional keys. Blank / missing values are skipped; the result is
    de-duplicated while preserving order.
    """
    emails: list[str] = []
    seen: set[str] = set()
    candidate_keys = [k for k in (email_field, "email", "e_mail", "emailaddress") if k]

    for entry in recipients:
        value = None
        if isinstance(entry, str):
            value = entry
        elif isinstance(entry, dict):
            for key in candidate_keys:
                raw = entry.get(key)
                if raw:
                    value = raw
                    break
        if not value:
            continue
        normalized = str(value).strip().lower()
        if normalized and normalized not in seen:
            seen.add(normalized)
            emails.append(normalized)

    return emails


def _build_attachments(raw_attachments: list) -> tuple[list[dict], str | None]:
    """Decode posted attachment descriptors into the SES attachment shape.

    Each descriptor is a dict with:
        - ``kind``: ``"csv"`` or ``"pdf"`` (drives default content type / extension), OR
          an explicit ``content_type``.
        - ``content_base64``: base64-encoded file bytes.
        - ``filename`` (optional): overrides the default ``members.<ext>`` name.

    Returns ``(attachments, error)`` — ``error`` is a message string if a descriptor
    was malformed (so the caller can return 400), else ``None``.
    """
    attachments: list[dict] = []

    for att in raw_attachments:
        if not isinstance(att, dict):
            return [], "Each attachment must be an object"

        content_b64 = att.get("content_base64")
        if not content_b64:
            return [], "Attachment is missing content_base64"

        try:
            content = base64.b64decode(content_b64, validate=True)
        except (binascii.Error, ValueError):
            return [], "Attachment content_base64 is not valid base64"

        kind = (att.get("kind") or "").lower()
        kind_defaults = _ATTACHMENT_KINDS.get(kind, {})
        content_type = att.get("content_type") or kind_defaults.get(
            "content_type", "application/octet-stream"
        )
        ext = kind_defaults.get("ext", "bin")
        filename = att.get("filename") or f"members.{ext}"

        attachments.append(
            {
                "filename": filename,
                "content": content,
                "content_type": content_type,
            }
        )

    return attachments, None


@members_mail_bp.route("/api/members/mail-set", methods=["POST"])
@cognito_required(required_permissions=[CAP_MEMBERS_EXPORT])
def mail_member_set(user_email, user_roles) -> ResponseReturnValue:
    """Send an analytics/filtered member set a mail via SES, optional attachment.

    Authorization: ``members:export`` capability required (R4.12).

    Request body::

        {
            "recipients": [ {<member row>} | "addr@example.com", ... ],
            "subject": "Subject line",
            "body": "<html or plain text body>",
            "email_field": "email",          # optional — key to read on each row
            "attachments": [                 # optional
                {"kind": "csv", "content_base64": "...", "filename": "members.csv"},
                {"kind": "pdf", "content_base64": "...", "filename": "labels.pdf"}
            ],
            "set_key": "members-per-type"    # optional — audit label only
        }

    Returns JSON with ``success`` and ``recipient_count`` on success, or an error.
    """
    try:
        # Tenant is ALWAYS resolved from the verified auth context — never trust a
        # client-supplied tenant (R8.2). No tenant => cannot scope the send.
        tenant = get_current_tenant(request)
        if not tenant:
            return jsonify({"error": "No tenant context"}), 400

        data = request.get_json(silent=True)
        if not data:
            return jsonify({"error": "No data provided"}), 400

        subject = (data.get("subject") or "").strip()
        body = data.get("body") or ""
        if not subject:
            return jsonify({"error": "Subject is required"}), 400
        if not body:
            return jsonify({"error": "Body is required"}), 400

        recipients = data.get("recipients")
        if not isinstance(recipients, list) or not recipients:
            return jsonify({"error": "No recipients provided"}), 400

        email_field = data.get("email_field")
        to_addresses = _extract_emails(recipients, email_field)
        if not to_addresses:
            # No resolvable email on any row — nothing to send (R1.4 / no-recipients).
            return jsonify({"error": "No recipient email addresses resolved"}), 400

        raw_attachments = data.get("attachments") or []
        if not isinstance(raw_attachments, list):
            return jsonify({"error": "attachments must be a list"}), 400
        attachments, att_error = _build_attachments(raw_attachments)
        if att_error:
            return jsonify({"error": att_error}), 400

        # Delegate to SES. BCC-by-default (R8.4): the visible envelope recipient is
        # the configured sender, every member goes on BCC so the recipient list is
        # never leaked across a bulk send.
        #
        # The decoded attachment bytes are the only transient artifact held in
        # memory (no temp file is written). They are released in the ``finally``
        # below once the send completes — success OR failure — so a bulk mail
        # never silently accumulates member PII in process memory (R8.5).
        from services.ses_email_service import SESEmailService

        ses = SESEmailService()

        try:
            result = ses.send_email_with_attachments(
                to_email=ses.sender,
                subject=subject,
                html_body=body,
                attachments=attachments,
                bcc=to_addresses,
                email_type="member_mail",
                administration=tenant,
                sent_by=user_email,
            )
        finally:
            # Release the held CSV/PDF bytes regardless of outcome (R8.5): drop the
            # decoded content from each descriptor, then clear the list so nothing
            # keeps the attachment buffers alive past the send.
            for att in attachments:
                att.pop("content", None)
            attachments.clear()

        if not result.get("success"):
            error = result.get("error")
            # An SES rate limit is a DISTINCT, recoverable failure (R4.12, ODI-4):
            # map it to 429 with a machine-readable code the client branches on to
            # show the dedicated "rate limit reached" message (keeping the set), vs
            # the generic 502 for any other SES failure.
            if _is_ses_rate_limited(error):
                logger.warning(
                    "SES rate-limited the member set mail for tenant %s: %s",
                    tenant,
                    error,
                )
                return jsonify(
                    {
                        "error": "Email send rate limit reached",
                        "code": "rate_limited",
                        "message": error,
                    }
                ), 429

            logger.error(
                "SES failed to mail member set for tenant %s: %s",
                tenant,
                error,
            )
            return jsonify(
                {"error": "Failed to send email", "message": error}
            ), 502

        logger.info(
            "Member set mailed by %s for tenant %s: %d recipient(s), set_key=%s",
            user_email,
            tenant,
            len(to_addresses),
            data.get("set_key"),
        )

        # Audit the send (R8.1/R8.3, Design C7): metadata only — actor, tenant,
        # set_key, a PII-free filter summary, the recipient count, and the output
        # kind. NO member PII (names/emails/addresses) is recorded. ``record_count``
        # is the resolved recipient count. Auditing must never take down a send that
        # already succeeded, so a failure here is swallowed (logged at warning).
        try:
            from services.analytics_audit import log_analytics_output

            log_analytics_output(
                actor=user_email,
                actor_roles=user_roles,
                tenant=tenant,
                output_kind="ses_mail",
                set_key=data.get("set_key"),
                record_count=len(to_addresses),
                filter_summary=data.get("filter_summary"),
            )
        except Exception as audit_error:  # noqa: BLE001 — audit must not fail a send
            logger.warning(
                "Member mail succeeded but audit logging failed for tenant %s: %s",
                tenant,
                audit_error,
            )

        return jsonify(
            {
                "success": True,
                "message": "Email sent successfully",
                "recipient_count": len(to_addresses),
                "message_id": result.get("message_id"),
            }
        )

    except Exception as e:  # noqa: BLE001 — route boundary: never leak a 500 stack
        logger.error("Error mailing member set: %s", e)
        return jsonify({"error": "Failed to send email", "message": str(e)}), 500
