---
title: "BTW aangifte"
author: "Peter Geers"
output:
  html_document:
  df_print: paged
  pdf_document: default
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
admin <- "GoodwinSolutions"
boekjaar <- "2025"
Q <- "3"
```

```{r getMutaties}

source("myFunctions.R")

packResult <- suppressMessages(getPackages(c("tidyverse","config", "lubridate","knitr", "RMariaDB")))
df <- suppressWarnings(getRecords("vw_mutaties"))

qMaand <- as.numeric(Q)*3
qDatum <- paste(boekjaar,sprintf("%02d", qMaand), "01", sep="-")
qDatum <- paste(boekjaar,sprintf("%02d", qMaand), days_in_month(qDatum), sep = "-")


```

Dit overzicht laat de gegevens zien voor de BTW aangifte van `r admin` Boekjaar `r boekjaar` en kwartaal `r Q` en opmaakdatum `r qDatum`

<h3>Eindbalans t/m `r qDatum`</h3>

```{r eindBalans}
## Subset beliow BalansDatum en specify Administration
balance <- subset(df, df$TransactionDate <= qDatum)
balance <- subset(balance, grepl(admin, balance$Administration))
balance <- subset(balance,grepl("2010|2020|2021",balance$Reknum))

balance <- balance %>% 
    group_by(Reknum, AccountName) %>% 
    reframe(amount = sum(Amount), .groups="drop")

kable(balance[1:3], row.names=FALSE)

```

<h3>Gegevens kwartaal `r boekjaar` - `r Q`</h3>

```{r kwartaalAnalyse}
vw <- subset(df, grepl(boekjaar, df$jaar))
vw <- subset(vw, grepl(admin, vw$Administration))
vw <- subset(vw, grepl(Q, vw$kwartaal))
vw <- subset(vw,grepl("2010|2020|2021|8001|8002|8003",vw$Reknum))

vw <- vw %>% 
    group_by(Reknum, AccountName) %>% 
    reframe(amount = sum(Amount), .groups="drop")
kable(vw[1:3], row.names=FALSE)
teBetalen <- round(sum(balance$amount),0)
betaalOpdracht <- ifelse(teBetalen >= 0, paste0(round(abs(teBetalen),0), " te ontvangen" ), 
                         paste0(round(abs(teBetalen),0)," te betalen"))
ontvangenBTW <- subset(vw, grepl("2020|2021", vw$Reknum))
ontvangenBTW <- round(sum(ontvangenBTW$amount),0)
voouitbetaaldeBTW <- round(ontvangenBTW - teBetalen,0)


## inloggegevens
url <- "https://mijnzakelijk.belastingdienst.nl/GTService/#/inloggen"

```

<ul>

<li>Netto € `r betaalOpdracht`</li>

<li>Ontvangen BTW € `r abs(ontvangenBTW)`</li>

<li>Vooruitbetaalde BTW € `r voouitbetaaldeBTW`</li>

</ul>

<a href=`r url`>Inloggen belastingdienst </a>
